platform :ios, '7.0'

pod 'AFNetworking', '~> 2.5.4'
pod 'XXNibBridge', '~> 2.1'
pod 'UIColor+Hex', '~> 1.0.1'
pod 'JSONModel','~>0.13.0'
pod 'SDWebImage', '~> 3.7.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'libextobjc', '~> 0.4.1'
pod 'MJRefresh', '~> 2.4.9'
pod 'Masonry'
pod 'Qiniu', '~> 7.0'
pod 'M13BadgeView', '~> 1.0.4'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'UITableView+FDTemplateLayoutCell'